name: belajarroutes
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animation_wrappers: ^3.0.0
  bloc: ^8.1.4
  calendar_slider: ^0.0.4
  cupertino_icons: ^1.0.2
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.1+2
  flutter_neat_and_clean_calendar: ^0.3.19+41
  flutter_qiblah: ^3.0.3
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  hijri: ^3.0.0
  hijriyah_indonesia: ^0.1.2
  intl: ^0.19.0
  islamic_hijri_calendar: ^0.0.4
  shared_preferences: ^2.2.3
  simple_gesture_detector: ^0.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/social/
    - assets/bottom_menu/
    - assets/home_top/
    - assets/icons/
    - assets/avatar/
